[toniwahrstaetter]
title = "Anton WahrstÃ¤tter's Blog"
url = "https://blog.toniwahrstaetter.com/"
entrySelector = "ul>li"
titleSelector = "h3"
linkSelector = "h3 a"
dateSelector = "span"
dateFormat = "MMM d, yyyy"
onFail = "error"
timeout = 120

[CharlieMarsh]
title = "Charlie Marsh's Articles"
url = "https://www.crmarsh.com/archive/"
entrySelector = "ul.posts-list>li"
titleSelector = "a"
linkSelector = "a"
onFail = "error"
timeout = 120


[graffioh]
title = "graffioh's blog"
url = "https://graffioh.com/blog/"
entrySelector = "ul > li"
titleSelector = "a"
linkSelector = "a"
dateSelector = "p"
dateFormat = "dd-MM-yyyy"
onFail = "stale"
timeout = 120
