[toniwahrstaetter]
title = "Anton WahrstÃ¤tter's Blog"
url = "https://blog.toniwahrstaetter.com/"
entrySelector = "ul>li"
titleSelector = "h3"
linkSelector = "h3 a"
dateSelector = "span"
dateFormat = "MMM d, yyyy"
onFail = "error"
timeout = 120
